name: Test
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  pull-requests: write
  
jobs:
  test-check:
    name: runner / fail-on-found (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          pattern: "TODO_DISCUSS_IN_THIS_COMMIT|TODO_IN_THIS_COMMIT"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / fail-on-found (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          pattern: "TODO_DISCUSS_IN_THIS_COMMIT|TODO_IN_THIS_COMMIT"
          workdir: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / fail-on-found (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          pattern: "TODO_DISCUSS_IN_THIS_COMMIT|TODO_IN_THIS_COMMIT"
          reviewdog_flags: -filter-mode=file -fail-on-error
